server:
  address: localhost
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/novelist
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

  # spring-security 설정
  profiles:
    include: oauth

  # spring-mail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: novelist456@gmail.com
    password: zlpdwptdkqgwskai
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace