spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: novelist456@gmail.com
    password: novelist123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true